[devent]

# the name of the devent
name="IPFS þing"

# the dates the devent runs
dateStart = "2022-07-11"
dateEnd = "2022-07-17"

# a pithy tag line you want to show in the "hero/splash" part of the landing page
tagline="""
_þing (n). thing, assembly, meeting, council. parliament._

A collaborative series of workshops for IPFS Implementors.
Hosted at the Harpa in Iceland.
"""

# a link to the devent website (what domain do you expect to use?)
link="https://2022.ipfs.camp"

# a link to a logo image for the event
logo="ipfs-logo.png"

# a link to a large res image for the hero/splash background.
# you likely want to use the devent location/city or something meaningful to the community
bgimg="harpa.jpg"

# the organizers of the devent (usually a group)
org="the IPFS Team"

# the website of the organizers
orglink="https://ipfs.io/team/"

# some text about the event -- will show up in the "About" section
# write a little or a lot, up to you.
about="""
IPFS þing (thing) is a week-long gathering of the IPFS implementor community with 
many separate tracks. 
There will be talks, workshops, hacking time, and more –
all dedicated to improving IPFS implementations.


## Venue

The event will happen at the [Harpa](https://goo.gl/maps/qQkLYrFprPMvAFaj7).

"""

# url for this event repo
repo="https://github.com/ipfs-shipyard/ipfs-thing-2022"

# list the participating teams.
# the format here is:
# [
#   ["Team Name", "https://team.org", "https://team.org/team-logo.jpg"],
# ]
teams = [
  ["Number Zero", "", "https://bafybeicftvbmvctgso22rtgvx43bql3g55p3x4a25bfnfkqqv3nwyfzewq.ipfs.dweb.link/number-zero-logo.png" ],
  ["Protocol Labs", "https://protocol.ai", "https://media.graphassets.com/e8bIG2apSUauy2dqK35W" ],
  ["PL Research", "https://research.protocol.ai", "https://research.protocol.ai/images/pl_research_logo.svg" ],
]

# this is a Frequently Asked Questions section.
#
# the format is:
# "Question here?" = """
# Answer here at length.
# """
[faq]

"What is IPFS þing?" = """
  IPFS þing is a collaborative workshop for the IPFS implementors community. <ADD MORE HERE>
"""

"Who is it for?" = """
  This invite-only event brings together maintainers or core contributors of an IPFS implementation, ranging from production usage to working demo. If this describes you and you haven't received an invitation, please email <@ipfs.io EMAIL ADDRESS THAT MOSH HAS REQUESTED>.
  
  If you are a user, tooling developer, <INSERT MYRIAD OF POSSIBLE ROLES HERE>, or curious community member, we enthusiastically invite you to IPFS Camp, an epic decentralized event organized by the community, for the community. Details on IPFS camp are coming soon, and will be announced on [twitter](https://twitter.com/ipfs).
"""

"How do I contact the organizers?" = """
  You can reach out to us at _____@_____.
"""

# this is a footer section, with any footer links you may want.
# there are three sections: links (general), legal (policy + terms), and social.
[footer]

[footer.links]
"IPFS" = "https://ipfs.io"
"Event Github" = "https://github.com/ipfs-shipyard/ipfs-thing-2022"

[footer.legal]
"Privacy Policy" = "#"
"Terms & Conditions" = "#"

[footer.social]
twitter = "ipfs"
github = "ipfs"
