[FILAustin]
name = "FIL Austin"
org = "Filecoin Foundation"
dri = "@claratsao"
website = "https://protocol.ai/labday"

date = "2022-06-08"
days = 1
times = "09:00 - 18:00"

attendees = "500"
difficulty = "All Are Welcome"
tags = ["Talks", "Discussions"]

description = """
FIL Austin is bringing the community together for workshops, panels, networking, and more – all dedicated to expanding the Filecoin network and growing the Web3 ecosystem. Join us IRL and in the Metaverse (details forthcoming).
"""

[LabDay]
name = "LabDay"
org = "Protocol Labs"
dri = "@jbenet"
website = "https://protocol.ai/labday"

date = "2022-06-06"
days = 2
times = "11:00 - 19:00"

attendees = "150"
tickets = "Waitlist"
difficulty = "All Are Welcome"
tags = ["Talks", "Workshops"]

description = """
This is a day of technical talks and workshops about projects across computing and innovation systems. Check out the line up on the website. Social gathering 17:00 - 19:00.
"""

[CryptoEconDay]
name = "CryptoEcon Day"
org = "CryptoEconLab"
dri = "@zixuanzh"
website = "TBD"

date = "2022-06-09"
days = 1
times = "10:00 - 16:00"

attendees = "100"
tickets = "Sold out"
difficulty = "All Are Welcome"
tags = ["Talks", "Discussions", "CryptoEcon"]

description = """
This event will provide a deep dive into CryptoEcon topics in Filecoin and other systems. Join us for a fun and educational look into the future of the fast-paced world of cryptoeconomics.
"""


[CryptoNetDinner]
name = "CryptoNet Dinner"
org = "CryptoNetLab"
dri = "@nicola"
website = "TBD"

date = "2022-06-10"
days = 1
times = "19:00 - 22:00"

attendees = "30"
tickets = "Invite Only"
difficulty = "Advanced"
tags = ["Dinner", "Discussions", "Cryptography"]

description = """
Join the cryptonet lab team for dinner and discuss SNARKs, Vector Commitments, Verifiable Computation, and lots of cool new cryptography. Come hungry!
"""

[FILAustinHack]
name = "FIL Austin Hack"
org = "CryptoEconLab"
dri = "@zixuanzh"
website = "TBD"

date = "2022-06-06"
days = 3
times = "10:00 - 24:00"

attendees = 300
tickets = "Tickets Available"
difficulty = "All Are Welcome"
tags = ["Hackathon"]

description = """
This event will provide a deep dive into CryptoEcon topics in Filecoin and other systems. Join us for a fun and educational look into the future of the fast-paced world of cryptoeconomics.
"""

