# the name of your track or event
name = "Project & Community"

# the name of the group organizing the event
org = ""

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@b5"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://ipfs-althing.io"

# the start date of the event
date = "2022-07-15"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:00 - 12:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "50"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["WIP", "Demos", "Hack Sessions"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """

This track aims to create space for advancing the IPFS project and community. New session proposals are welcome, especially those that focus on a specific, actionable subtopic rather than attempting to grapple with project and community stewardship.

Currently, we have reserved a 1/2 day for this track. If enough sessions are proposed, this track will be extended into Friday afternoon.

"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots

[[timeslots]]
startTime="09:00"
speakers=["@mishmosh"]
title="Welcome standup discussion"
description="A brief introduction to the track"

[[timeslots]]
startTime="09:15"
speakers=["@lidel"]
title="Lightweight RFC Process"
description="A walkthrough of the new RFC process and its motivations, updated specs repository, and how you can submit an RFC."

[[timeslots]]
startTime="09:45"
speakers=[]
title="Open Slot"
description=""

[[timeslots]]
startTime="10:15"
speakers=[]
title="Open Slot"
description=""

[[timeslots]]
startTime="10:45"
speakers=["@mishmosh"]
title="Reorienting the website"
description="IPFS's public presence predominantly communicates that there are 2 IPFS implementations, js-ipfs and go-ipfs. It also communicates that the project is essentially PL-owned. During this session, we will re-orient some key landing pages toward today's Cambrian explosion of new implementations. This is intended to a fairly surgical co-working session, with a short discussion to kick off and then each participant creating PRs."

[[timeslots]]
startTime="11:30"
speakers=["TBD, maybe @b5 and @mishmosh"]
title="Fireside chat: Funding and Sustainability"
description=""
