name = "CryptoNet Dinner"
org = "CryptoNetLab"
dri = "@nicola"
website = "TBD"

date = "2022-06-10"
days = 1
times = "19:00 - 22:00"

attendees = "30"
tickets = "Invite Only"
difficulty = "Advanced"
tags = ["Dinner", "Discussions", "Cryptography"]

description = """
Join the cryptonet lab team for dinner and discuss SNARKs, Vector Commitments, Verifiable Computation, and lots of cool new cryptography. Come hungry!
"""
