name = "CryptoEcon Day"
org = "CryptoEconLab"
dri = "@zixuanzh"
website = "TBD"

date = "2022-06-09"
days = 1
times = "10:00 - 16:00"

attendees = "100"
tickets = "Sold out"
difficulty = "All Welcome"
tags = ["Talks", "Discussions", "CryptoEcon"]

description = """
This event will provide a deep dive into CryptoEcon topics in Filecoin and other systems. Join us for a fun and educational look into the future of the fast-paced world of cryptoeconomics.
"""
