name = "FIL Austin Hack"
org = "CryptoEconLab"
dri = "@zixuanzh"
website = "TBD"

date = "2022-06-06"
days = 3
times = "10:00 - 24:00"

attendees = 300
tickets = "Tickets Available"
difficulty = "All Welcome"
tags = ["Hackathon"]

description = """
This event will provide a deep dive into CryptoEcon topics in Filecoin and other systems. Join us for a fun and educational look into the future of the fast-paced world of cryptoeconomics.
"""

